"""SQLAlchemy ORM models for database tables."""

from datetime import datetime
from typing import Any

from sqlalchemy import JSON, DateTime, Float, Index, Integer, String, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    pass


class ProposalHistory(Base):
    """Store historical proposals generated by the system."""

    __tablename__ = "proposal_history"

    id: Mapped[str] = mapped_column(String(100), primary_key=True)
    profile_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    job_title: Mapped[str] = mapped_column(String(300), nullable=False)
    job_description: Mapped[str] = mapped_column(Text, nullable=False)
    job_summary: Mapped[str] = mapped_column(String(500), nullable=False)
    proposal_text: Mapped[str] = mapped_column(Text, nullable=False)
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False)
    matched_skills: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    relevant_projects: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    skill_match_percentage: Mapped[float] = mapped_column(Float, nullable=False)
    budget_alignment: Mapped[str] = mapped_column(String(50), nullable=False)
    timeline_feasibility: Mapped[str] = mapped_column(String(50), nullable=False)
    budget_range: Mapped[str | None] = mapped_column(String(100), nullable=True)
    tokens_used: Mapped[int] = mapped_column(Integer, nullable=False)
    cost_usd: Mapped[float] = mapped_column(Float, nullable=False)
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    retrieval_chunks: Mapped[int] = mapped_column(Integer, nullable=False)
    extra_metadata: Mapped[dict[str, Any]] = mapped_column(JSON, nullable=True, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    __table_args__ = (
        Index("idx_profile_created", "profile_id", "created_at"),
        Index("idx_confidence", "confidence_score"),
    )

    def to_dict(self) -> dict[str, Any]:
        """Convert model instance to dictionary."""
        return {
            "id": self.id,
            "profile_id": self.profile_id,
            "job_title": self.job_title,
            "job_description": self.job_description,
            "job_summary": self.job_summary,
            "proposal_text": self.proposal_text,
            "confidence_score": self.confidence_score,
            "matched_skills": self.matched_skills,
            "relevant_projects": self.relevant_projects,
            "skill_match_percentage": self.skill_match_percentage,
            "budget_alignment": self.budget_alignment,
            "timeline_feasibility": self.timeline_feasibility,
            "budget_range": self.budget_range,
            "tokens_used": self.tokens_used,
            "cost_usd": self.cost_usd,
            "latency_ms": self.latency_ms,
            "retrieval_chunks": self.retrieval_chunks,
            "extra_metadata": self.extra_metadata,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }
